/* Package a Cloudflare Pages bundle for direct upload: jdt-tender-hub.zip
 *
 *   npm run zip
 *
 * The ZIP contains the static site plus a self-contained `_worker.js`
 * (generated from functions/api/analyse.js) so the /api/analyse AI proxy works
 * even via dashboard drag-and-drop — which does not compile the functions/
 * directory the way Git/Wrangler deploys do. functions/api/analyse.js stays the
 * single source of truth; the worker is generated from it at pack time.
 *
 * Deploy: Cloudflare dashboard → Workers & Pages → Create → Pages → Upload
 * assets → upload this ZIP. Then set the ANTHROPIC_API_KEY secret (DEPLOY.md).
 */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const root = path.resolve(__dirname, "..");

// 1. Build the static site into public/
require("./build-web.js");

// 2. Generate a self-contained advanced-mode _worker.js from the Pages Function.
//    Strip the `export` keywords so the handlers become local, then add a fetch
//    entrypoint that routes /api/analyse and serves everything else from ASSETS.
const fnSrc = fs.readFileSync(path.join(root, "functions", "api", "analyse.js"), "utf8")
  .replace(/export\s+async\s+function/g, "async function");
const worker = "/* GENERATED by scripts/pack-zip.js from functions/api/analyse.js — do not edit. */\n\n" +
  fnSrc + "\n\n" +
  "export default {\n" +
  "  async fetch(request, env, ctx) {\n" +
  "    const url = new URL(request.url);\n" +
  "    if (url.pathname === \"/api/analyse\") {\n" +
  "      const context = { request: request, env: env, ctx: ctx };\n" +
  "      if (request.method === \"POST\") return onRequestPost(context);\n" +
  "      if (request.method === \"GET\") return onRequestGet(context);\n" +
  "      return new Response(\"Method Not Allowed\", { status: 405 });\n" +
  "    }\n" +
  "    return env.ASSETS.fetch(request);\n" +
  "  }\n" +
  "};\n";

// 3. Stage the static output + the generated worker.
const stage = path.join(root, ".deploy-zip");
fs.rmSync(stage, { recursive: true, force: true });
fs.cpSync(path.join(root, "public"), stage, { recursive: true });
fs.writeFileSync(path.join(stage, "_worker.js"), worker);

// 4. Zip the staged contents (paths relative to the bundle root).
const zipPath = path.join(root, "jdt-tender-hub.zip");
fs.rmSync(zipPath, { force: true });
execFileSync("zip", ["-r", "-q", zipPath, "."], { cwd: stage });
fs.rmSync(stage, { recursive: true, force: true });

const kb = (fs.statSync(zipPath).size / 1024).toFixed(0);
console.log("Built jdt-tender-hub.zip (" + kb + " KB) — static site + _worker.js (AI proxy). Upload via Cloudflare Pages; set ANTHROPIC_API_KEY to enable AI.");
